### ISSUE TITLE
Batch processing

### ISSUE THREAD

**Issue by gzaffagnini** [embl-cba/spindle3d#36]
Hi @tischi,
In the user guide I've seen mentioned the possibility to run Spindle3D in batch, but I couldn't find it in the actual plugin. Is there any possibility to run Spindle3D automatically on a series of images in a folder? Thanks a lot!

**Comment by TobiasKletter** [comment]
Hi @gzaffagnini 

thanks for your message, we shall describe the batch processing in the manual a bit clearer!

You can access the batch processing when you type in "spindle3D" in the Fiji search bar. It will suggest a couple of commands in the list on the left. With the command "Spindle 3D process file" selected, press the "batch" button in the righthand corner (it will look slightly different because we removed the Advanced option for now):

![image](https://user-images.githubusercontent.com/45814595/172127291-8fde85e4-2cab-4077-8774-70ac274e9492.png)

In the next dialogue that pops up, make sure you select inputImageFile as the parameter to batch process and select your files. The next dialogue will be the Spindle3D window where you then can specify your settings. 

Please let us know if this worked for you, and thanks again for raising the issue!
Best,
Tobias

**Comment by gzaffagnini** [comment]
Hi @TobiasKletter, thanks a lot for your quick and detailed reply! I figured out how to get to the window you included in the screenshot and could run in batch mode, now my workflow is very smooth! Thanks also so much for your entire work together with @tischi, the plugin is fantastic and is allowing me to make accurate quantifications on mouse oocyte spindles in different conditions. I think that as a community we need this kind of tools for more precise and reproducible quantifications, and Spindle3D is definitely a strong help for those - like me - that have little to none programming ability. I sincerely hope I'll be able to include this analysis in the final version of my paper (so far looking good on the first dataset) to give you the credit you deserve and help disseminating your great work. All the best and thanks again!

**Comment by TobiasKletter** [comment]
Thanks @gzaffagnini for the kind words and for using the plugin! Good luck with your project, and let us know if you run into any hiccups!

**Comment by gzaffagnini** [comment]
Dear Tobias,
Thank you very much for your quick and detailed reply! I just managed to run the batch mode, I realised I needed to activate the full search bar option in fiji, before I had only the mini search bar available in the help menu. And also thank you so much for your work, I am willing to quantify the spindle morphometrics in mouse oocytes upon different treatment and was amazed when I found your plugin and paper! As a community these tools are super important for robust reliable quantifications that can be replicated among groups, and also help a lot those like me that have little knowledge in programming :) I just finished analysing the first small dataset running the plugin manually and it looks very promising, so I am really looking forward to run it in batch now and analyse the whole datasets. I sincerely hope I’ll be able to include the results in my paper to give your work the credit it deserves and help disseminating it!

Perhaps in the future if you would be willing to implement a new feature, I think it would be nice if at least in batch mode the results were saved in a single file for direct import into excel.
Thanks again and all the best,

Gabri


Gabriele Zaffagnini PhD
Oocyte Biology and Cellular Dormancy group
Centre for Genomic Regulation (CRG) - Dr. Aiguader 88 - 08003 Barcelona (Spain)
***@***.*** ***@***.***>

**Comment by tischi** [comment]
> Perhaps in the future if you would be willing to implement a new feature, I think it would be nice if at least in batch mode the results were saved in a single file for direct import into excel.

TBH, I don't think we want to do this.
What software are you using for downstream analysis?
If you are using R I could share code with you to automatically join tables.
